INSERT INTO Authentification (email, mdp) VALUES ('admin', 'admin1234');

INSERT INTO Salon (nom, adresse) VALUES ('analakely', 'La potiniere, Av. de L independance, Antananarivo');
INSERT INTO Salon (nom, adresse) VALUES ('ankadifotsy', 'Ankadifotsy Antananarivo, 101');
INSERT INTO Salon (nom, adresse) VALUES ('alarobia', 'Immeuble RIA II I 2A Morarano Alarobia Antananarivo, 101');
INSERT INTO Salon (nom, adresse) VALUES ('tamatave', 'RCV7+9JC, 501 Rue Des Hovas, Toamasina');

INSERT INTO Types (nom) VALUES ('Interne');
INSERT INTO Types (nom) VALUES ('Externe');

INSERT INTO Genre (nom) VALUES ('Homme');
INSERT INTO Genre (nom) VALUES ('Femme');

INSERT INTO Service (nom, idtypes) VALUES
    ('Caissier', 2),
    ('Commercial', 1),
    ('Coiffeur', 1),
    ('Coloriste', 1),
    ('Estheticien', 1),
    ('Onglerie', 1),
    ('POLYVALENT', 1),
    ('Masseuse', 1),
    ('Tatooeur', 1),
    ('Prothesite ongulaire', 1),
    ('Maquilleur', 1),
    ('Femme de menage', 2),
    ('Magasinier', 2),
    ('Responsable salon', 2),
    ('Accueil', 2),
    ('Gardien', 2),
    ('Formateur', 2),
    ('Assistante de direction', 2),
    ('RH - Assistante DG', 2),
    ('Developpeur', 2),
    ('Graphiste Designer', 2),
    ('Coursier', 2),
    ('Employe Polivalent', 2),
    ('Securite', 2),
    ('Comptable', 2),
    ('CDG', 2),
    ('ADM', 2),
    ('Marketing', 2);


INSERT INTO Employe (nom,prenom,idgenre,isinternship) VALUES
    ('RANDRIANARIVELO ','MAMINIAINA HERITIANA',1,0),
    ('ANDRIAMBOLOLONA ','NOROANJA SARAH',2,0),
    ('RAKOTORAHALAHY ','SAFIDY JEAN RICO',1,0),
    ('ANDRIAMAMPIONONA','JEAN MARIE MICHAEL',1,0),
    ('HERINASANDRATRA','LOUIS THIERRY',1,0),
    ('RAKOTOMALALA','ROLAND ERNEST (HERY)',1,0),
    ('RAFALIMANANTSOA','HOBINIAINA FLEUVIA',2,0),
    ('RAMARO HERINIONY ','RIGO DAJASY',1,0),
    ('ANDRIATSILAVINA','JONATHAN',1,0),
    ('RANAIVOSON VOAHANGY','TIANA',2,0),
    ('RASOARIMALALA','VEROLALAO',2,0),
    ('RAVELONJANAHARY','LALATIANA CYNTHIA',2,0),
    ('HERINJAKA','FITIA LAETICIA',2,0),
    ('ZANAKOLONIRINA','',2,0),
    ('RASOLONIRINA ','LUCIE',2,0),
    ('ANDRIATIANIAINA','ARTHUR',1,0),
    ('RAHANTARISOA','TANTELY NIAINA',1,0),
    ('RAKOTONIAINA','JEAN CHRISTOPHE (MAHERY)',1,0),
    ('RAVONIARISOA','RAVAKA MIORA',2,0),
    ('RASOAMBOLAMANANA','SARAH MANITRA ELIANAH',2,0),
    ('RASENDRARIVONY','YANDHIE',2,0),
    ('RAKOTONJATOVO','HAJANIAINA (JAHIA)',1,0),
    ('RAHARINORONIRIANA','SARAH',2,0),
    ('HAINGONIRIANA FANOMEZANTSOA','AIMMA',2,0),
    ('RAZAFIMBELO','HARISON LUC JOH',1,0),
    ('RAKOTONIRINA','VAHATRINIHOAVY MAMITANTELY',1,0),
    ('FITAHIANA','OLIVA',2,0),
    ('RAFANOMEZANTSOA','FRANCIA TINAH',2,0),
    ('RAZAFIMBELO','HERITIANA STEPHANE',2,0),
    ('RASOLOMANANA','HERY JANIE',2,0),
    ('RATSIMBAZAFY','HODIA CHRISTINNE',2,0),
    ('RAKOTOARIVONY','ROVANIAINA ZOMAMPIONONA',2,0),
    ('SOLONIAINA','FANDRESENA',1,0),
    ('RANDRIANOMANANA','TSILAVINA ALBERT',1,0),
    ('KASINA ','CORINNE',2,0),
    ('ANDRIANAIVOARIMANANA','AINAHARISOA',2,0),
    ('ANDRIAMANANTENA','JOHANNES PERLYS',2,1),
    ('RAMIALISATA','MIORA HARIMALALA',2,1),
    ('ANDRIAMIARINTSOA ','HERINIRINA ANGELO',2,1),
    ('RAHAINGOARISOA ','NATHALIE',2,1),
    ('NITOVOFENOANJANAHARY','LANCIA',2,1),
    ('MIARINJAKA ','RINASOA',2,1),
    ('RANDRIANARIVONY ','ANDO FINARITRA',2,1),
    ('RAZAFY ','ANDRIANIRINASOA KARINA',2,1);

INSERT INTO Employe (nom,prenom,idgenre,isinternship) VALUES
    ('RAKOTOMANANA','MICHAEL',1,0),
    ('RANDRIANJAFY','ZO TOAVINA',2,0),
    ('RAHANTAHARISOA','SUZANNE',2,0),
    ('RAHARIVOLOLONA','JOELLINE (ZO)',2,0),
    ('RALOVATIANA ','JEAN LOUIS',1,0),
    ('RABOANARISON ','FIDERANA',2,0),
    ('RAHANITRINIAINA','RINDRASOA DOMOINA',2,0),
    ('RAMAROLAHY Maminiaina ','NOHAVISOA',2,0),
    ('RANOMENJANAHARY','FRANCIA',2,0),
    ('HERIMALALA','MAMITIANA',2,0),
    ('RAVAOARIMANANA','CHARLOTTE MAYAVE',2,0),
    ('RAVOARIMALALA','NATACHA',2,0),
    ('RANDRIANJATOVO ','JOCELYNE',2,0),
    ('RAHARILALAINA ','FANJA DOMOINA SOPHIE',2,1),
    ('RAFIDINIRINA ','TENDRY',2,1),
    ('RAHERIARISON','MARCELLA',2,1),
    ('RAKOTONIRINA','TOJOSOA JEAN MODESTE',2,1),
    ('ANDRIANJATOVO ','MALALA ANGELA',2,1);

INSERT INTO Employe (nom,prenom,idgenre,isinternship) VALUES
    ('MAMINIRINA ','TOVO',1,0),
    ('RAZAFINDRAKOTO ','ANDRIAMISEDRA DIMBY NIAINA',1,0),
    ('RABARISON ','JULIO NICOLAS AVOTRA',1,0),
    ('ANDRIAMPARANY ','CLAUDIA',2,0),
    ('HOBINATENAINA','DALLY ESTHELA',2,0),
    ('ANDRIAMAMONJISOA ','NARINDRA',2,0),
    ('RATSIORIMALALA','HASINA RAVOLAHANTA',2,0),
    ('RAZAFINDRAKOTO','SAMBATRA MITIA',2,0),
    ('RAHARIMALALA ','TOLOJANAHARY',2,0),
    ('RAHELINIRINA','FANIRISOA MARIE SYLVIA',2,0),
    ('RAVAOARISOA','MAMINIRINA FABIENNE',2,0),
    ('MILANTOLANTOSOA ','MORASAMBATRA C. STUDY',2,0),
    ('RAKOTOMALALA','NJAKA TIANA JIMMY',1,0),
    ('RANDRIAMAMPIONONA ','HERINIRINA MODESTE',1,0),
    ('HOLINOMENANTENAINARINIVO','THANIA',2,0),
    ('RATSIMBAZAFY','NARINDRA DESIRELLE',2,0),
    ('NANTENAINDRINOMENJANAHARY','MARC EDESSE SOJA CHRIST',2,0),
    ('RASOARIMALALA HENIKAJA','MISAELA',1,0),
    ('RAFANOMEZANTSOA ','FINARITRA',2,0),
    ('RAHARINIRINA NORONIRIANA','SARAH (STG)',2,0),
    ('MAHOLY HARISON','NATHALIE',2,0),
    ('FANJANIRINA','ARTHUR (HASINA)',2,0),
    ('RAKOTONDRAMPARANY','AINA MICHEL',2,0),
    ('RAHELIARIMALALA','HANITRA VOLOLONA',2,0),
    ('RANIKAELISOA','MONOLIE',2,0),
    ('RANDRIA','FARATIANA TSIRY VOLOLONA',2,0),
    ('ROSON','FINOANA LILIANE (LILA)',2,0),
    ('RAVALIMANANA ','MARIANNE',2,0),
    ('FALIMANANA','MODESTE (FETRA)',2,0),
    ('RANARIVELO','JACOB ELIE (YEMIE)',1,0),
    ('RANDRIANARISOA','LOHARANO NOMENJANAHARY FY',1,0),
    ('ANDRIAMAMPIRAISINA','GINA MARIA',2,0),
    ('RASOARIMANANA','VOLATIANA GINAH',2,1),
    ('NOMENJANAHARY','RAVAKINIAINA MAMITIANA',2,1),
    ('RAJAONARISON','FANOMEZANTSOA PATRIC',2,1),
    ('RAMAROSON','TSIFERANA AVOTRA',2,1),
    ('RAFARAMALALA','HERINIAINA PHILBERTINE',2,1),
    ('RANDRIANASOLO','RINA STEPHAN',2,1),
    ('ANDRIAMANAMPISOA ','LAHATRA ANDONIAINA',2,1),
    ('RAVONIARINDRINA','HAINGO TIANA',2,1),
    ('MAMINIRINA ','TOKY NOMENA',2,1),
    ('RAKOTOARIMANANA','HERY NIAINA',2,1),
    ('RASOAMANARIVO ','MARIE ERICA',2,1),
    ('HARIMANDIMBY ','VALISOA MICKAEL',2,1),
    ('RAFALIHERY','KANTONIAINA MICHAEL (JAMES)',1,0);

INSERT INTO Employe (nom,prenom,idgenre,isinternship) VALUES
    ('RABETANY ','LAZANDRAINY JEAN PIERRE',1,0),
    ('ANDRIANIRINA','RAVAKA',2,0),
    ('RAFENONIRIANA','JAMES',1,0),
    ('RAHELIARISOA','HASINIAINA',2,0),
    ('ZAFINIRINA','MARIE PATRICIA',2,0),
    ('RAZAFINARIVONY','DINA TANTELY',2,0),
    ('FANAMPISOA','NIRINA ROMAIN',1,0),
    ('ANDRIANASOLO','ANJARAMALALA NIAINA ONJATIANA T.',1,0),
    ('RAMINOHASINA','VALOHERISOA MIORA',2,0),
    ('RAKOTOMALALA','VONJINIAINA RAISSA',2,0),
    ('RANOROMALALA ','ONJANIRIANA IANTSOTIANA SANDRA',2,0),
    ('HANTANIRINA','FRANCINE',2,0),
    ('RANDRIANARISON ','MARIELLE',2,0),
    ('CHEN LAI','SARAH KETAKANDRIANA',2,0),
    ('ANDRIAMIHAJA ','FINARITRINIAINA',2,1);

INSERT INTO EmployeService (idemploye, idservice, idsalon) VALUES
    (1,15,1),
    (2,15,1),
    (3,1,1),
    (4,3,1),
    (5,3,1),
    (6,3,1),
    (7,3,1),
    (8,5,1),
    (9,5,1),
    (10,5,1),
    (11,5,1),
    (12,5,1),
    (13,5,1),
    (14,12,1),
    (15,12,1),
    (16,16,1),
    (17,6,1),
    (18,6,1),
    (19,6,1),
    (20,6,1),
    (21,6,1),
    (22,6,1),
    (23,6,1),
    (24,6,1),
    (25,6,1),
    (26,6,1),
    (27,6,1),
    (28,6,1),
    (29,6,1),
    (30,6,1),
    (31,6,1),
    (32,6,1),
    (33,6,1),
    (34,6,1),
    (35,10,1),
    (36,14,1),
    (37,6,1),
    (38,6,1),
    (39,6,1),
    (40,6,1),
    (41,6,1),
    (42,6,1),
    (43,6,1),
    (44,6,1),
    --Ankadifotsy
    (45,1,2),
    (46,3,2),
    (47,3,2),
    (48,12,2),
    (49,13,2),
    (50,6,2),
    (51,6,2),
    (52,6,2),
    (53,6,2),
    (54,6,2),
    (55,6,2),
    (56,6,2),
    (57,6,2),
    (58,6,2),
    (59,6,2),
    (60,6,2),
    (61,6,2),
    (62,6,2),
    --Ivandry
    (63,1,3),
    (64,1,3),
    (64,2,3),
    (64,2,3),
    (65,3,3),
    (66,3,3),
    (67,3,3),
    (67,5,3),
    (68,3,3),
    (68,5,3),
    (69,3,3),
    (69,5,3),
    (70,3,3),
    (70,5,3),
    (71,3,3),
    (71,5,3),
    (72,3,3),
    (72,5,3),
    (73,3,3),
    (73,5,3),
    (74,3,3),
    (74,5,3),
    (74,6,3),
    (75,7,3),
    (76,5,3),
    (76,6,3),
    (77,5,3),
    (78,12,3),
    (79,12,3),
    (80,13,3),
    (81,8,3),
    (82,6,3),
    (83,6,3),
    (84,6,3),
    (85,6,3),
    (86,6,3),
    (87,6,3),
    (88,6,3),
    (89,6,3),
    (90,6,3),
    (91,6,3),
    (92,6,3),
    (92,11,3),
    (93,14,3),
    (94,14,3),
    (95,6,3),
    (96,6,3),
    (97,6,3),
    (98,6,3),
    (99,6,3),
    (100,6,3),
    (101,6,3),
    (102,6,3),
    (103,6,3),
    (104,6,3),
    (105,6,3),
    (106,6,3),
    (107,9,3),
    --Tamatave
    (108,3,4),
    (108,4,4),
    (109,3,4),
    (109,6,4),
    (110,5,4),
    (111,5,4),
    (112,5,4),
    (113,12,4),
    (114,16,4),
    (115,13,4),
    (116,6,4),
    (117,6,4),
    (118,6,4),
    (119,6,4),
    (120,6,4),
    (121,14,4),
    (122,6,4);

INSERT INTO Question (Question) VALUES 
    ('Comment évaluez-vous la qualité de service au salon ?'),
    ('Le personnel du salon a-t-il répondu à vos besoins et à vos attentes ?'),
    ('Comment trouvez-vous l ambiance et le confort du salon ?'),
    ('Pensez-vous que les tarifs du salon sont raisonnables par rapport à la qualité des services ?');

INSERT INTO Reponse (idquest, valeur, reponse) VALUES 
    (1,1,'Bonne'),
    (1,2,'Moyenne'),
    (1,3,'Médiocre'),
    (2,1,'Oui, totalement'),
    (2,2,'Oui, partiellement'),
    (2,3,'Non, pas du tout'),
    (3,1,'Bien'),
    (3,2,'Pas trop à l aise'),
    (3,3,'Pas bien du tout'),
    (4,1,'Raisonnables'),
    (4,2,'Neutres'),
    (4,3,'Un peu eleves');

insert into ReseauxSociaux (nom) values ('Facebook'),('Instagram'),('Tiktok');

insert into Influenceur(nom,email,code) values
    ('Micky','anialysue@gmail.com','Micky_love'),
    ('Meva Kely','ramiariramalalameva@gmail.com','Meva_Kely'),
    ('Francka Audrey','franckaaudrey@gmail.com','Audrey_fra'),
    ('Estelle','estellebaot@gmail.com','Estelle_bao'),
    ('Fy','fyrajaonarivelo007@gmail.com','Fy_261'),
    ('Sandra Gomez','sandra.paper@icloud.com','Sandra_go');

insert into InfluenceurReseauxSociaux(idinfluenceur,idreseauxsociaux,followers) values
(1,1,265000),
(1,2,),
(1,3,),

(2,1,134000),
(2,2,),
(2,3,),

(3,1,),
(3,2,),
(3,3,),

(4,1,),
(4,2,),
(4,3,),

(5,1,),
(5,2,),
(5,3,),

(6,1,),
(6,2,),
(6,3,);